### ISSUE TITLE
Compiled js file name issue in build

### ISSUE THREAD

**Issue by Oddadmix** [do0dleman/do0dle-colors#2]
Firstly, amazing work on the package, it's nice and unique.

I am getting a build issue when trying to build my overall project on ubuntu machine.

```Error [PLUGIN_ERROR]: Cannot find module '/root/actions-runner/_work/node_modules/do0dle-colors/lib/conversionFunctions/OkLChToRgb.js' imported from /root/actions-runner/_work/node_modules/do0dle-colors/lib/color/color.js
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:418:11)
    at moduleResolve (node:internal/modules/esm/resolve:981:10)
    at defaultResolve (node:internal/modules/esm/resolve:1078:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36)
```

Looks like the generated file `lib/conversionFunctions/OkLChToRgb.js` in the published version https://registry.npmjs.org/do0dle-colors/-/do0dle-colors-2.1.3.tgz is named as `OkLChtoRgb.js` not `OkLChToRgb.js` as referenced in `lib/color/color.js`

I would appreciate if you could fix that in a new version.

**Comment by do0dleman** [comment]
Can You provide Node version and `package.json` that You are using in your project?

**Comment by Oddadmix** [comment]
@do0dleman , It's in the published tar

https://registry.npmjs.org/do0dle-colors/-/do0dle-colors-2.1.3.tgz
<img width="774" alt="Screenshot 2023-12-28 at 9 04 18 PM" src="https://github.com/do0dleman/do0dle-colors/assets/1205162/98e24493-1125-4157-a416-6e012b614775">

Here the file in the pack is OkLCh**t**oRgb.js vs the one imported in `do0dle-colors/lib/color/color.js` it's OkLCh**T**oRgb.js

Probably if a Windows machine used to pack and publish the package it won't complain about the build as it's case insensitive. 

I hope that helps.

**Comment by do0dleman** [comment]
@Oddadmix, thank You for your response. It helped a lot.

I have changed file names and imports in `v2.1.4.` accordingly. 

Since I cannot test the package on Linux, could you please provide feedback on this fix?

I hope it works.

**Comment by Oddadmix** [comment]
Looks good, I just tried the `2.1.4` and it's working fine.

Thanks for the fix
